
#### EHBO bezoeken met een vriend of vriendin

##### Determinantenstructuur

De intentie om de EHBO te bezoeken met een vriend of vriendin is relatief hoog, met een gemiddelde boven de zes (op een zevenpuntschaal). Van de drie determinanten van intentie die zijn gemeten, is perceived norm het hoogst, ook met een gemiddelde boven de zes, gevolgd door attitude, met een gemiddelde net onder de zes, en tot slot perceived behavioral control, met een gemiddelde iets boven de vijf. Kortom: deelnemers zijn overtuigd dat hun sociale omgeving er positief tegenover staat als ze een vriend of vriendin meenemen naar de EHBO; evalueren dit zelf ook positief; en hebben relatief veel vertrouwen dat ze dat ook goed kunnen.

Zowel attitude, perceived norm, als perceived behavioral control voorspellen intentie: perceived norm heel sterk, attitude iets minder sterk, en perceived behavioral control nog minder sterk. Dit patroon is logisch gegeven de zogenaamde 'verdelingsvormen' van deze variabelen. Bij intentie scoren de meeste mensen heel hoog, terwijl bij perceived behavioral control deelnemers wat lager scoren. In zo'n geval geldt dat het maximaal haalbare verband wat lager is dan als beide variabelen dezelfde verdelingsvorm hebben.

Al met al suggereert deze determinantenstructuur dat er bij de meeste bezoekers geen interventie nodig lijkt. Zo lang zij niet in paniek raken (en hun gedrag dus beredeneerd, 'reasoned', blijft) lijkt de kans groot dat zij vriend(inn)en meenemen naar de EHBO als dat nodig is. Maar, perceived behavioral control is wat minder hoog onder deze deelnemers dan je zou willen, en voor een aantal deelnemers zit de intentie rond de drie, vier, of lager (op een zevenpuntschaal). Er is hier dus nog ruimte voor verbetering.

##### Sub-determinanten (opvattingen) binnen attitude

Met betrekking tot de EHBO bezoeken met een vriend(in) bleken de verwachtingen ('expectancies' of 'attitudinal beliefs') amper samen te hangen met de direct gemeten attitude of met intentie. Dit is interessant, want dit is in strijd met de verwachtingen die we van te voren hadden. De gemeten verwachtingen zijn immers die waarvan de project-, advies-, en expertcommissies en de Unity peers hadden verwacht dat ze een rol zouden spelen bij de intentie om met een vriend(in) naar de EHBO te gaan. Het kan zijn dat dit wordt verklaard door de hoge intenties die werden gevonden, maar het is ook aannemelijk dat er andere verwachtingen zijn die een rol spelen. Er zou kwalitatief onderzoek nodig zijn om dit te bevestigen of ontkrachten.

##### Sub-determinanten (opvattingen) binnen waargenomen norm

Waargenomen norm ('perceived norm') lijkt een relevante voorspeller van intentie. Met betrekking tot de EHBO bezoeken met een vriend(in) is dit ook logisch: dat betreft immers deels die vriend(in). Daarnaast is er vaak een positieve norm met betrekking tot altruistisch gedrag ('hulp-gedrag'). Zoals bij veel gedrag gerelateerd aan het uitgaansleven was de goedkeuring van familie (ouders, broers en zussen) niet zo belangrijk als die van partner en (beste) vriend(inn)en. Interventies kunnen zich dus het beste richten op peers (i.e. leeftijds/levensstijl/subcultuur genoten).

Descriptieve norm liet hetzelfde patroon zien. De inschatting was dat 'andere mensen op een feest' minder snel met een vriend(in) naar de EHBO zouden gaan dan iemands naaste vriend(inn)en. De inschatting van het gedrag van 'andere mensen op een feest' had echter amper voorspellende waarde voor waargenomen norm en intentie, dus dit lijkt geen zinvol interventiedoel.

##### Sub-determinanten (opvattingen) binnen waargenomen gedragscontrole

Deelnemers waren redelijk overtuigd dat de EHBO een vriend(in) met een probleem zou kunnen helpen: bijna niemand scoorde onder de drie of vier (op een zevenpuntschaal). Deze overtuiging hing (zwak maar toch) samen met algemene waargenomen gedragscontrole en intentie. Er zat meer spreiding in de overtuiging dat deelnemers wisten hoe ze een vriend(in) die zich niet goed voelt mee konden krijgen naar de EHBO.

Deze overtuiging hing ook samen met algemene waargenomen gedragscontrole en intentie, en het lijkt dus zinvol om mensen hierin te ondersteunen. Ze kunnen bijvoorbeeld geadviseerd worden om van te voren af te spreken wat ze doen als iemand zich niet goed voelt; of om elke keer een primaire verantwoordelijke persoon aan te wijzen waarbij de afspraak dan is dat daar altijd naar geluisterd wordt (de bob lijkt de meest logische persoon); of om af te spreken altijd met z'n tweeen naar de EHBO te gaan.

#### Zelf de EHBO bezoeken

Determinanten van zelf de EHBO bezoeken zijn gemeten voor drie situaties: met een lichte klacht, met een alcohol-gerelateerde klacht, en met een middelen-gerelateerde klacht. Deze drie situaties zullen tegelijk worden besproken.

##### Determinantenstructuur

De intentie om de EHBO te bezoeken stijgt naarmate de klacht minder gangbaar is: de intentie om met een lichte klacht de EHBO te bezoeken ligt gemiddeld tussen de drie en de vier, met een alcohol-gerelateerde klacht tussen de vier en de vijf, en met een middelen-gerelateerde klacht tussen de vijf en de zes. Enerzijds is dit goed nieuws; deze stijging weerspiegelt de relatieve ernst. Anderzijds zijn feestbezoekers niet altijd in staat de juiste diagnose te maken.

Bij een lichte klacht zitten attitude en waargenomen norm gemiddeld tussen de vier en de vijf (op een zevenpuntschaal), terwijl waargenomen gedragscontrole hoger ligt, met een gemiddelde tussen de vijf en de zes. Attitude en waargenomen norm zijn zeer sterke voorspellers van intentie om de EHBO te bezoeken, en waargenomen gedragscontrole is een zwakkere voorspeller, waarschijnlijk omdat die gemiddeld hoger is en minder spreiding heeft (oftewel: er is minder variatie tussen mensen).

Bij een alcoholgerelateerde klacht is de waargenomen gedragscontrole iets lager dan bij een lichte klacht, en lijkt waargenomen norm een iets sterkere voorspeller van intentie dan attitude. Waargenomen gedragscontrole is weer een wat zwakkere voorspeller, maar hoger dan bij een lichte klacht.

Bij een middelengerelateerde klacht zijn de attitude en waargenomen norm hoger dan bij een lichte of alcoholgerelateerde klacht, terwijl de waargenomen gedragscontrole nog weer iets lager ligt. De verbanden tussen deze determinanten en intentie zijn weer heel sterk, en ditmaal heeft ook waargenomen gedragscontrole een sterk verband.

##### Sub-determinanten (opvattingen) binnen attitude

De meeste deelnemers hebben middelsterk tot sterk de opvatting dat een lichte klacht vanzelf overgaat, en hoe sterker deelnemers deze opvatting hebben, hoe minder snel ze naar de EHBO gaan. Opvattingen waren verdeeld met betrekking tot of je met een lichte klacht op de beveiliging kon afstappen: de meeste deelnemers dachten dat dit zou kunnen, maar toch goed een derde was hier nog niet zo zeker over. De meeste deelnemers, maar niet allemaal, verwachten dat als ze naar de EHBO zouden gaan met een lichte klacht, dat hun ouders dan niet gewaarschuwd zouden worden, dat ze anoniem zouden blijven, dat ze terug mochten naar het feest, dat de politie niet zou worden gebeld, en dat ze niet van het feest verwijderd zouden worden door de beveiliging. Echter, sommige deelnemers verwachten dit juist wel.

Een deel van de bezoekers gaf aan dat bezoek aan de EHBO door en lichte klacht de avond of dag zou verpesten. Dit hing niet sterk samen met intentie of attitude. HIervoor geldt echter weer dat de verdelingsvorm dit kan verklaren: omdat de meeste bezoekers niet vonden dat een EHBO-bezoek de avond of dag zou verpesten, kan het zijn dat dit verband wordt onderschat.

Met betrekking tot een alcoholgerelateerde klacht verschijnen er twee patronen. Ten eerste zijn minder deelnemers overtuigd van zaken als hun anonimiteit, dat de politie niet wordt gebeld, en dat ze daarna terug mogen naar het feest. Ten tweede hangen deze opvattingen wat sterker samen met intentie om de EHBO te bezoeken met een alcoholgerelateerde klacht.

Dit patroon zet nog wat verder door als het om middelengerelateerde klachten gaat.

Kortom: het lijkt verstandig om het beleid op elk feest duidelijk te communiceren. Voor zover het beleid per feest afwijkt, zou het verstandig zijn om hier een lijn in te trekken, zodat communicatie met bezoekers makkelijker en eenduidiger wordt. Vanuit gezondsheidsoogpunt zou het beleid erop gericht moeten zijn toegang tot de EHBO zo laagdrempelig mogelijk te maken.

##### Sub-determinanten (opvattingen) binnen waargenomen norm

Het was al duidelijk dat waargenomen norm een rol speelt bij het meenemen van een vriend(in) naar de EHBO. Waargenomen norm blijkt ook ook een rol te spelen bij zelf de EHBO bezoeken. Ouders/verzorgers worden, zoals meestal bij uitgaansleven-gerelateerd gedrag, niet als relevante sociale referenten gezien. Het kan dus goed zijn als mensen met elkaar bespreken hoe ze tegenover EHBO-bezoek staan. Gegeven de brede positieve sociale norm lijkt dit een veilige route. Descriptieve norm was ook een sterke voorspeller van intentie: oftewel, als deelnemers aangaven dat andere mensen naar de EHBO zouden gaan met een lichte, alcoholgerelateerde, of middelengerelateerde klacht, dan was hun intentie om dat zelf te doen ook hoger.

##### Sub-determinanten (opvattingen) binnen waargenomen gedragscontrole

Net als bij het meenemen van een vriend(in) naar de EHBO gold ook bij het zelf bezoeken van de EHBO dat overtuiging die te kunnen vinden, en dat de EHBO zou kunnen helpen, een rol speelden bij de intentie om de EHBO te bezoeken met een lichte, alcoholgerelateerde, of middelengerelateerde klacht. Het benadrukken dat de EHBO in (bijna) alle gevallen kan helpen, en waar deze te vinden is, lijkt dus handig. Indien gewenst kan de beveiliging ook worden ingezet om mensen naar de EHBO te begeleiden, wat dan vervolgens natuurlijk ook moet worden gecommuniceerd aan bezoekers.
